version: "2"
services:
  comit-admin:
    container_name: comit-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    working_dir: /app
    volumes:
      - ./:/app
    command: yarn start
    env_file:
      - .env.local